Add missing declaration for ensureZeroTerminated
Fixes: src/bumblebeed.c:171:5: warning: implicit declaration of function
‘ensureZeroTerminated’ [-Wimplicit-function-declaration]

The missing declaration did not affect the fixes made in da77e37 and c0babc1 (at
least for gcc) as bbsocket.o is already included.